# Generated by Django 4.2.8 on 2023-12-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.CharField(choices=[('Mercedes - Benz', 'Mercedes - Benz'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Volkswagen', 'Volkswagen'), ('Chevrolet', 'Chevrolet'), ('Renault', 'Renault'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Fiat', 'Fiat'), ('Hyundai', 'Hyundai'), ('Peugeot', 'Peugeot'), ('Lexus', 'Lexus'), ('Kia', 'Kia'), ('Citroën', 'Citroën'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Chery', 'Chery'), ('Jeep', 'Jeep')], max_length=50, verbose_name='Marca')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], max_length=50, verbose_name='Combustível')),
                ('tipo', models.CharField(choices=[('Econômico', 'Econômico'), ('Intermediário', 'Intermediário'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Executivo', 'Executivo'), ('Pick-UP', 'Pick-UP'), ('Minivan', 'Minivan')], max_length=100, verbose_name='Categoria')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sobre o carro')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('placa', models.CharField(error_messages={'unique': 'Veículo já cadastrado!'}, max_length=15, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Foto')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da diária')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Locador',
                'verbose_name_plural': 'Locadores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('cpfcnpj', models.CharField(max_length=18, verbose_name='CPF:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Foto')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=100, verbose_name='Sexo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário:')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_do_contrato', models.DateField(verbose_name='Data de Retirada do Carro')),
                ('fim_do_contrato', models.DateField(verbose_name='Data da Devolução do Carro')),
                ('forma_de_pagamento', models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Boleto', 'Boleto'), ('PIX', 'PIX'), ('Transferência', 'Transferência'), ('Espécie', 'Espécie'), ('Outro', 'Outro')], max_length=100, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=12)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Veículo', to='aluguel.carro', verbose_name='Veículo')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='aluguel.usuario', verbose_name='Locatário')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
