# Generated by Django 4.2.8 on 2023-12-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_usuario_cpfcnpj_alter_usuario_data_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='total_diarias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Diárias'),
        ),
    ]
