# Generated by Django 4.2.8 on 2023-12-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_contrato_total_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
